interface WeightLossPlan {
  summary: string;
  bmi: number;
  bmiCategory: string;
  exerciseCalendar: Array<{
    day: string;
    activity: string;
    duration: number;
    calories: number;
  }>;
  nutrition: {
    dailyCalories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  timeline: {
    weeksToGoal: number;
    weeklyWeightLoss: string | number;
  };
}

// Translation object for PDF export
const pdfTranslations: Record<string, Record<string, string>> = {
  en: {
    title: "Weight Loss Plan",
    personalizedFor: "Personalized for",
    yourPlan: "Your Plan",
    healthMetrics: "Health Metrics",
    healthSummary: "Health Summary",
    currentBMI: "Current BMI",
    category: "Category",
    weeksToGoal: "Weeks to Goal",
    nutrition: "Nutrition",
    dailyCalories: "Daily Calories",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    percentage: "% of daily intake",
    exercise: "Exercise Schedule",
    exerciseCalendar: "Exercise Calendar",
    day: "Day",
    activity: "Activity",
    duration: "Duration (min)",
    totalExerciseCalories: "Total Calories",
    totalDuration: "Total Duration",
    generatedBy: "Generated by Health AI Assistant",
    dailyNutrition: "Daily Nutrition",
    nutritionBreakdown: "Nutrition Breakdown",
    macroDistribution: "Macro Distribution",
    weightProgress: "Weight Progress",
    timeline: "Timeline",
    tips: "Tips & Recommendations",
    timelineToGoal: "Timeline to Goal",
    timeline_: "Estimated Timeline",
    weeks: "weeks",
    months: "months",
    tips_: "Tips",
    disclaimer: "Important Disclaimer",
    disclaimerText:
      "This plan is for reference only. Please consult a healthcare professional before starting any new exercise or diet program.",
  },
  vi: {
    title: "Lộ Trình Giảm Cân",
    personalizedFor: "Được cá nhân hóa cho",
    yourPlan: "Lộ Trình Của Bạn",
    healthMetrics: "Chỉ Số Sức Khỏe",
    healthSummary: "Tóm Tắt Sức Khỏe",
    currentBMI: "BMI Hiện Tại",
    category: "Phân Loại",
    weeksToGoal: "Tuần",
    nutrition: "Dinh Dưỡng",
    dailyCalories: "Calo Hàng Ngày",
    calories: "Calo",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Chất Béo",
    percentage: "% lượng nạp hàng ngày",
    exercise: "Lịch Tập Luyện",
    exerciseCalendar: "Lịch Tập Luyện",
    day: "Ngày",
    activity: "Hoạt Động",
    duration: "Thời Lượng (phút)",
    totalExerciseCalories: "Tổng Calo",
    totalDuration: "Tổng Thời Lượng",
    generatedBy: "Được tạo bởi Health AI Assistant",
    dailyNutrition: "Dinh Dưỡng Hàng Ngày",
    nutritionBreakdown: "Phân Tích Dinh Dưỡng",
    macroDistribution: "Phân Bố Macro",
    weightProgress: "Tiến Độ Giảm Cân",
    timeline: "Thời Gian",
    tips: "Lời Khuyên & Gợi Ý",
    timelineToGoal: "Thời Gian Đạt Mục Tiêu",
    timeline_: "Thời Gian Dự Kiến",
    weeks: "tuần",
    months: "tháng",
    tips_: "Lời Khuyên",
    disclaimer: "Lưu Ý Quan Trọng",
    disclaimerText:
      "Lộ trình này chỉ mang tính chất tham khảo. Vui lòng tư vấn với chuyên gia y tế trước khi bắt đầu chương trình.",
  },
};

function getTranslation(locale: string, key: string): string {
  const lang = locale === "vi" ? "vi" : "en";
  return pdfTranslations[lang][key] || key;
}

// Helper function to escape HTML special characters
function sanitizeAndFormatText(text: string): string {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

  return escaped.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}

export function generatePDF(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
) {
  downloadPDFAsHTML(plan, userName, locale);
}

// Main function to export as HTML
export async function downloadPDFAsHTML(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
) {
  try {
    const htmlContent = generatePDFContent(plan, userName, locale);
    const file = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(file);

    const link = document.createElement("a");
    link.href = url;
    link.download = `weight-loss-plan-${userName}-${Date.now()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Download error:", error);
  }
}

// Generate comprehensive HTML with charts and all content
function generatePDFContent(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
): string {
  // Calculate nutrition percentages
  const proteinCals = plan.nutrition.protein * 4;
  const carbsCals = plan.nutrition.carbs * 4;
  const fatCals = plan.nutrition.fat * 9;

  const proteinPercent = Math.round(
    (proteinCals / plan.nutrition.dailyCalories) * 100,
  );
  const carbsPercent = Math.round(
    (carbsCals / plan.nutrition.dailyCalories) * 100,
  );
  const fatPercent = Math.round((fatCals / plan.nutrition.dailyCalories) * 100);

  // Calculate exercise totals
  const totalCalories = plan.exerciseCalendar.reduce(
    (sum, e) => sum + e.calories,
    0,
  );
  const totalDuration = plan.exerciseCalendar.reduce(
    (sum, e) => sum + e.duration,
    0,
  );

  // Create exercise table rows
  const exerciseTableRows = plan.exerciseCalendar
    .map(
      (item) =>
        `<tr><td class="table-cell">${item.day}</td><td class="table-cell">${item.activity}</td><td class="table-cell">${item.duration}</td><td class="table-cell">${item.calories}</td></tr>`,
    )
    .join("");

  // Get BMI category color
  const getBMICategoryColor = (category: string) => {
    if (category === "Underweight" || category === "Thiếu cân")
      return "#1890ff";
    if (category === "Normal" || category === "Bình thường") return "#52c41a";
    if (category === "Overweight" || category === "Thừa cân") return "#faad14";
    return "#ff4d4f";
  };

  const weeksToMonths = Math.round(plan.timeline.weeksToGoal / 4);

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${getTranslation(locale, "title")}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    html, body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
      line-height: 1.6;
      color: #333;
    }
    body {
      background: #f5f7fa;
      padding: 20px;
    }
    .container {
      background-color: white;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #1890ff;
      padding-bottom: 30px;
      margin-bottom: 40px;
    }
    .header h1 {
      color: #1890ff;
      margin: 0 0 10px 0;
      font-size: 32px;
      font-weight: 700;
    }
    .header .subtitle {
      color: #666;
      font-size: 16px;
      margin: 5px 0;
    }
    .header .date {
      color: #999;
      font-size: 12px;
      margin-top: 10px;
    }
    .section {
      margin-bottom: 40px;
      page-break-inside: avoid;
    }
    .section-title {
      display: flex;
      align-items: center;
      gap: 12px;
      color: #1890ff;
      font-size: 22px;
      font-weight: 600;
      margin-bottom: 20px;
      padding-bottom: 12px;
      border-bottom: 3px solid #1890ff;
    }
    .icon { font-size: 24px; }
    .card {
      background: #f9f9f9;
      border: 1px solid #f0f0f0;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
    }
    .summary-box {
      background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%);
      border-left: 5px solid #1890ff;
      padding: 20px;
      border-radius: 8px;
      line-height: 1.8;
      font-size: 14px;
      margin-bottom: 20px;
      white-space: pre-wrap;
      word-wrap: break-word;
    }
    .grid-2 {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }
    .grid-3 {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
    }
    .grid-4 {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 15px;
    }
    .stat-box {
      background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%);
      border: 2px solid #1890ff;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    .stat-value {
      font-size: 32px;
      font-weight: 700;
      color: #1890ff;
      margin-bottom: 8px;
    }
    .stat-label {
      font-size: 12px;
      color: #666;
      font-weight: 600;
    }
    .nutrition-box {
      background: linear-gradient(135deg, #fff5f0 0%, #ffe7d5 100%);
      border: 2px solid #ff7a45;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    .nutrition-box.carbs {
      background: linear-gradient(135deg, #fff7e6 0%, #ffe8b6 100%);
      border-color: #faad14;
    }
    .nutrition-box.carbs .nutrition-value { color: #faad14; }
    .nutrition-box.fat {
      background: linear-gradient(135deg, #fff1f0 0%, #ffccc7 100%);
      border-color: #f5222d;
    }
    .nutrition-box.fat .nutrition-value { color: #f5222d; }
    .nutrition-value {
      font-size: 32px;
      font-weight: 700;
      color: #ff7a45;
      margin-bottom: 8px;
    }
    .nutrition-label {
      font-size: 12px;
      color: #666;
      font-weight: 600;
      margin-bottom: 5px;
    }
    .nutrition-percent {
      font-size: 14px;
      color: #ff7a45;
      font-weight: 600;
    }
    .nutrition-box.carbs .nutrition-percent { color: #faad14; }
    .nutrition-box.fat .nutrition-percent { color: #f5222d; }
    .pie-section {
      display: flex;
      gap: 40px;
      margin: 30px 0;
      align-items: flex-start;
      page-break-inside: avoid;
    }
    .pie-container {
      flex: 0 0 200px;
    }
    .pie-chart-wrapper {
      position: relative;
      width: 180px;
      height: 180px;
      border-radius: 50%;
      background: conic-gradient(
        #9254de 0deg calc(${proteinPercent * 3.6}deg),
        #faad14 calc(${proteinPercent * 3.6}deg) calc(${(proteinPercent + carbsPercent) * 3.6}deg),
        #ff7a45 calc(${(proteinPercent + carbsPercent) * 3.6}deg) 360deg
      );
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 auto;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }
    .pie-center {
      width: 140px;
      height: 140px;
      background: white;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-size: 16px;
      font-weight: 700;
      color: #333;
    }
    .pie-legend {
      flex: 1;
      display: flex;
      flex-direction: column;
      gap: 15px;
    }
    .legend-item {
      display: flex;
      align-items: center;
      gap: 12px;
      font-size: 14px;
    }
    .legend-color {
      width: 20px;
      height: 20px;
      border-radius: 4px;
      flex-shrink: 0;
    }
    .legend-color.protein { background: #9254de; }
    .legend-color.carbs { background: #faad14; }
    .legend-color.fat { background: #ff7a45; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
      border: 1px solid #f0f0f0;
    }
    thead tr {
      background: linear-gradient(135deg, #1890ff 0%, #1677d2 100%);
      color: white;
    }
    th {
      padding: 15px;
      text-align: left;
      font-weight: 700;
      font-size: 13px;
    }
    td {
      padding: 12px 15px;
      border-bottom: 1px solid #f0f0f0;
      font-size: 13px;
    }
    .table-cell {
      padding: 12px 15px;
    }
    tbody tr:nth-child(odd) { background-color: #fafafa; }
    tbody tr:hover { background-color: #f0f5ff; }
    .exercise-summary {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 20px;
      page-break-inside: avoid;
    }
    .exercise-stat {
      background: linear-gradient(135deg, #f6f8fb 0%, #e6f2ff 100%);
      border: 2px solid #1890ff;
      padding: 20px;
      border-radius: 8px;
      text-align: center;
    }
    .exercise-stat.calories {
      background: linear-gradient(135deg, #fff1f0 0%, #ffccc7 100%);
      border-color: #f5222d;
    }
    .exercise-stat.calories .stat-value { color: #f5222d; }
    .stat-value { font-size: 32px; font-weight: 700; color: #1890ff; }
    .stat-label { font-size: 12px; color: #666; font-weight: 600; margin-top: 8px; }
    .tips-list {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .tips-list li {
      padding: 12px 15px;
      background: #f9f9f9;
      border-left: 4px solid #52c41a;
      border-radius: 4px;
      font-size: 13px;
    }
    .disclaimer-box {
      background-color: #fff7e6;
      border-left: 4px solid #faad14;
      padding: 15px;
      border-radius: 4px;
      color: #d48806;
      font-size: 12px;
      margin-top: 20px;
      page-break-inside: avoid;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #f0f0f0;
      color: #999;
      font-size: 11px;
    }
    @media print {
      body { background: white; padding: 0; }
      .container { box-shadow: none; padding: 20px; }
      .section { page-break-inside: avoid; }
    }
    @media (max-width: 768px) {
      .grid-2, .grid-3, .grid-4 { grid-template-columns: 1fr; }
      .pie-section { flex-direction: column; gap: 20px; }
      .pie-container { width: 100%; }
      .pie-chart-wrapper { margin: 0 auto; }
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>💪 ${getTranslation(locale, "title")}</h1>
      <div class="subtitle">${getTranslation(locale, "personalizedFor")} <strong>${userName}</strong></div>
      <div class="date">${new Date().toLocaleDateString(locale === "en" ? "en-US" : "vi-VN", { year: "numeric", month: "long", day: "numeric" })}</div>
    </div>

    <!-- Summary Section -->
    <div class="section">
      <div class="section-title"><span class="icon">❤️</span> ${getTranslation(locale, "healthSummary")}</div>
      <div class="summary-box">${sanitizeAndFormatText(plan.summary)}</div>
      
      <div class="grid-4">
        <div class="stat-box">
          <div class="stat-value">${plan.bmi}</div>
          <div class="stat-label">${getTranslation(locale, "currentBMI")}</div>
        </div>
        <div class="stat-box" style="background: linear-gradient(135deg, #f6ffed 0%, #d9f7be 100%); border-color: #52c41a;">
          <div class="stat-value" style="color: #52c41a;">${plan.bmiCategory}</div>
          <div class="stat-label">${getTranslation(locale, "category")}</div>
        </div>
        <div class="stat-box" style="background: linear-gradient(135deg, #fff7e6 0%, #ffe8b6 100%); border-color: #faad14;">
          <div class="stat-value" style="color: #faad14;">${plan.timeline.weeksToGoal}</div>
          <div class="stat-label">${getTranslation(locale, "weeksToGoal")}</div>
        </div>
        <div class="stat-box" style="background: linear-gradient(135deg, #fff1f0 0%, #ffccc7 100%); border-color: #f5222d;">
          <div class="stat-value" style="color: #f5222d;">${plan.timeline.weeklyWeightLoss}</div>
          <div class="stat-label">kg/${locale === "en" ? "Week" : "Tuần"}</div>
        </div>
      </div>
    </div>

    <!-- Exercise Section -->
    <div class="section">
      <div class="section-title"><span class="icon">💪</span> ${getTranslation(locale, "exerciseCalendar")}</div>
      
      <div class="exercise-summary">
        <div class="exercise-stat">
          <div class="stat-value">${totalDuration}</div>
          <div class="stat-label">${locale === "en" ? "Total Minutes" : "Tổng Phút"}</div>
        </div>
        <div class="exercise-stat calories">
          <div class="stat-value">${totalCalories}</div>
          <div class="stat-label">${locale === "en" ? "Total Calories" : "Tổng Calo"}</div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>${getTranslation(locale, "day")}</th>
            <th>${getTranslation(locale, "activity")}</th>
            <th>${getTranslation(locale, "duration")}</th>
            <th>${getTranslation(locale, "calories")}</th>
          </tr>
        </thead>
        <tbody>${exerciseTableRows}</tbody>
      </table>
    </div>

    <!-- Nutrition Section -->
    <div class="section">
      <div class="section-title"><span class="icon">🍽️</span> ${getTranslation(locale, "dailyNutrition")}</div>
      
      <div class="card">
        <div style="margin-bottom: 20px;">
          <div style="font-weight: 600; margin-bottom: 10px; font-size: 16px; color: #333;">${getTranslation(locale, "dailyCalories")}</div>
          <div style="background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%); padding: 20px; border-radius: 8px; text-align: center;">
            <div style="font-size: 32px; font-weight: 700; color: #1890ff;">${plan.nutrition.dailyCalories} kcal</div>
          </div>
        </div>
      </div>

      <div class="grid-3">
        <div class="nutrition-box">
          <div class="nutrition-label">Protein</div>
          <div class="nutrition-value">${plan.nutrition.protein}g</div>
          <div class="nutrition-percent">${proteinPercent}%</div>
        </div>
        <div class="nutrition-box carbs">
          <div class="nutrition-label">Carbs</div>
          <div class="nutrition-value">${plan.nutrition.carbs}g</div>
          <div class="nutrition-percent">${carbsPercent}%</div>
        </div>
        <div class="nutrition-box fat">
          <div class="nutrition-label">Fat</div>
          <div class="nutrition-value">${plan.nutrition.fat}g</div>
          <div class="nutrition-percent">${fatPercent}%</div>
        </div>
      </div>

      <div style="margin-top: 30px; page-break-inside: avoid;">
        <h3 style="font-size: 16px; color: #333; margin-bottom: 15px; font-weight: 600;">${getTranslation(locale, "macroDistribution")}</h3>
        <div class="pie-section">
          <div class="pie-container">
            <div class="pie-chart-wrapper">
              <div class="pie-center">${proteinPercent}%</div>
            </div>
          </div>
          <div class="pie-legend">
            <div class="legend-item">
              <div class="legend-color protein"></div>
              <span><strong>Protein:</strong> ${plan.nutrition.protein}g (${proteinPercent}%)</span>
            </div>
            <div class="legend-item">
              <div class="legend-color carbs"></div>
              <span><strong>Carbs:</strong> ${plan.nutrition.carbs}g (${carbsPercent}%)</span>
            </div>
            <div class="legend-item">
              <div class="legend-color fat"></div>
              <span><strong>Fat:</strong> ${plan.nutrition.fat}g (${fatPercent}%)</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Timeline & Tips Section -->
    <div class="section">
      <div class="section-title"><span class="icon">📋</span> ${getTranslation(locale, "timeline")} & ${getTranslation(locale, "tips")}</div>
      
      <div class="card">
        <h3 style="font-size: 16px; color: #1890ff; margin-bottom: 15px; font-weight: 600;">📅 ${getTranslation(locale, "timeline_")}</h3>
        <div style="background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%); padding: 20px; border-radius: 8px; margin-bottom: 20px;">
          <div style="font-size: 20px; font-weight: 700; color: #1890ff; margin-bottom: 10px;">
            ${plan.timeline.weeksToGoal} ${getTranslation(locale, "weeks")} (${weeksToMonths} ${getTranslation(locale, "months")})
          </div>
          <div style="font-size: 13px; color: #666;">
            ${locale === "en" ? "Weekly loss rate:" : "Mức giảm/tuần:"} <strong>${plan.timeline.weeklyWeightLoss} kg</strong>
          </div>
        </div>
      </div>

      <div class="card">
        <h3 style="font-size: 16px; color: #52c41a; margin-bottom: 15px; font-weight: 600;">✓ ${getTranslation(locale, "tips_")}</h3>
        <ul class="tips-list">
          <li>💧 ${locale === "en" ? "Drink enough water (2-3L per day) to stay hydrated and boost metabolism" : "Uống đủ nước (2-3 lít/ngày) để giữ ẩm và tăng trao đổi chất"}</li>
          <li>😴 ${locale === "en" ? "Get 7-8 hours of sleep daily for optimal recovery and muscle building" : "Ngủ đủ 7-8 tiếng/ngày để phục hồi tối ưu và xây dựng cơ bắp"}</li>
          <li>📊 ${locale === "en" ? "Track your weight weekly and keep a food journal to maintain consistency" : "Check weight hàng tuần và ghi chép lại thực phẩm hàng ngày"}</li>
          <li>🥗 ${locale === "en" ? "Focus on whole foods, lean proteins, and balanced nutrition" : "Tập trung vào thực phẩm nguyên chất, protein và cân bằng dinh dưỡng"}</li>
          <li>⏰ ${locale === "en" ? "Follow your meal schedule consistently and avoid late-night snacking" : "Tuân thủ giờ ăn nhất quán và tránh ăn vặt lúc khuya"}</li>
          <li>🏥 ${locale === "en" ? "Consult a healthcare professional or nutritionist for personalized advice" : "Tư vấn bác sĩ hoặc chuyên gia dinh dưỡng để được lời khuyên cá nhân hóa"}</li>
        </ul>
      </div>

      <div class="disclaimer-box">
        <strong>⚠️ ${getTranslation(locale, "disclaimer")}</strong><br><br>
        ${getTranslation(locale, "disclaimerText")}
      </div>
    </div>

    <!-- Footer -->
    <div class="footer">
      <p>${getTranslation(locale, "generatedBy")} | ${new Date().toLocaleString(locale === "en" ? "en-US" : "vi-VN")}</p>
      <p style="margin-top: 10px; font-size: 10px;">✓ ${locale === "en" ? "This document has been optimized for printing and viewing on all devices" : "Tài liệu này được tối ưu hóa để in ấn và xem trên tất cả các thiết bị"}</p>
    </div>
  </div>
</body>
</html>`;
}
