interface WeightLossPlan {
  summary: string;
  bmi: number;
  bmiCategory: string;
  exerciseCalendar: Array<{
    day: string;
    activity: string;
    duration: number;
    calories: number;
  }>;
  nutrition: {
    dailyCalories: number;
    protein: number;
    carbs: number;
    fat: number;
  };
  timeline: {
    weeksToGoal: number;
    weeklyWeightLoss: string | number;
  };
}

// Translation object for PDF export
const pdfTranslations: Record<string, Record<string, string>> = {
  en: {
    title: "Weight Loss Plan",
    personalizedFor: "Personalized for",
    yourPlan: "Your Plan",
    healthMetrics: "Health Metrics",
    currentBMI: "Current BMI",
    category: "Category",
    weeksToGoal: "Weeks to Goal",
    nutrition: "Nutrition",
    dailyCalories: "Daily Calories",
    calories: "Calories",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",
    percentage: "% of daily intake",
    exercise: "Exercise Schedule",
    day: "Day",
    activity: "Activity",
    duration: "Duration (min)",
    totalExerciseCalories: "Total Calories",
    totalDuration: "Total Duration",
    generatedBy: "Generated by Health AI Assistant",
  },
  vi: {
    title: "Lộ Trình Giảm Cân",
    personalizedFor: "Được cá nhân hóa cho",
    yourPlan: "Lộ Trình Của Bạn",
    healthMetrics: "Chỉ Số Sức Khỏe",
    currentBMI: "BMI Hiện Tại",
    category: "Phân Loại",
    weeksToGoal: "Tuần",
    nutrition: "Dinh Dưỡng",
    dailyCalories: "Calo Hàng Ngày",
    calories: "Calo",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Chất Béo",
    percentage: "% lượng nạp hàng ngày",
    exercise: "Lịch Tập Luyện",
    day: "Ngày",
    activity: "Hoạt Động",
    duration: "Thời Lượng (phút)",
    totalExerciseCalories: "Tổng Calo",
    totalDuration: "Tổng Thời Lượng",
    generatedBy: "Được tạo bởi Health AI Assistant",
  },
};

function getTranslation(locale: string, key: string): string {
  const lang = locale === "vi" ? "vi" : "en";
  return pdfTranslations[lang][key] || key;
}

// Helper function to escape HTML special characters
function sanitizeAndFormatText(text: string): string {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

  return escaped.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}

export function generatePDF(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
) {
  downloadPDFAsHTML(plan, userName, locale);
}

// Main function to export as HTML
export async function downloadPDFAsHTML(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
) {
  try {
    const htmlContent = generatePDFContent(plan, userName, locale);
    const file = new Blob([htmlContent], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(file);

    const link = document.createElement("a");
    link.href = url;
    link.download = `weight-loss-plan-${userName}-${Date.now()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Download error:", error);
  }
}

// Generate comprehensive HTML with charts and all content
function generatePDFContent(
  plan: WeightLossPlan,
  userName: string,
  locale: string = "vi",
): string {
  // Calculate nutrition percentages
  const proteinCals = plan.nutrition.protein * 4;
  const carbsCals = plan.nutrition.carbs * 4;
  const fatCals = plan.nutrition.fat * 9;

  const proteinPercent = Math.round(
    (proteinCals / plan.nutrition.dailyCalories) * 100,
  );
  const carbsPercent = Math.round(
    (carbsCals / plan.nutrition.dailyCalories) * 100,
  );
  const fatPercent = Math.round((fatCals / plan.nutrition.dailyCalories) * 100);

  // Calculate exercise totals
  const totalCalories = plan.exerciseCalendar.reduce(
    (sum, e) => sum + e.calories,
    0,
  );
  const totalDuration = plan.exerciseCalendar.reduce(
    (sum, e) => sum + e.duration,
    0,
  );

  // Create exercise table rows
  const exerciseTableRows = plan.exerciseCalendar
    .map(
      (item) =>
        `<tr><td>${item.day}</td><td>${item.activity}</td><td>${item.duration}</td><td>${item.calories}</td></tr>`,
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="${locale}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${locale === "en" ? "Weight Loss Plan" : "Lộ trình Giảm Cân"}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      padding: 40px 20px;
      max-width: 1000px;
      margin: 0 auto;
      background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    }
    .container {
      background-color: white;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 10px 30px rgba(0,0,0,0.2);
    }
    .page-break {
      page-break-after: always;
      margin-bottom: 40px;
      padding-bottom: 40px;
      border-bottom: 3px dashed #e0e0e0;
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #1890ff;
      padding-bottom: 30px;
      margin-bottom: 30px;
    }
    .header h1 {
      color: #1890ff;
      margin: 0;
      font-size: 32px;
      font-weight: 700;
    }
    .header p {
      color: #666;
      margin: 10px 0 0 0;
      font-size: 16px;
    }
    .section {
      margin-bottom: 35px;
    }
    .section h2 {
      color: #1890ff;
      border-left: 5px solid #1890ff;
      padding-left: 15px;
      margin-top: 0;
      font-size: 22px;
      margin-bottom: 20px;
    }
    .summary {
      background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%);
      padding: 20px;
      border-left: 5px solid #1890ff;
      border-radius: 8px;
      line-height: 1.8;
      white-space: pre-wrap;
      font-size: 14px;
      margin-bottom: 20px;
    }
    .stats-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-bottom: 20px;
    }
    .stat-card {
      background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%);
      padding: 20px;
      border-radius: 8px;
      text-align: center;
      border: 2px solid #1890ff;
    }
    .stat-value { font-size: 28px; font-weight: bold; color: #1890ff; }
    .stat-label { color: #555; font-size: 12px; margin-top: 8px; font-weight: 600; }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
      border: 1px solid #ddd;
    }
    thead tr {
      background: linear-gradient(135deg, #1890ff 0%, #1677d2 100%);
      color: white;
    }
    th {
      padding: 15px;
      text-align: left;
      font-weight: 700;
      font-size: 13px;
    }
    td {
      padding: 12px 15px;
      border-bottom: 1px solid #f0f0f0;
      font-size: 13px;
    }
    tbody tr:nth-child(odd) { background-color: #fafafa; }
    tbody tr:hover { background-color: #f0f5ff; }
    .nutrition-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      margin: 20px 0;
    }
    .nutrition-item {
      background: linear-gradient(135deg, #fff5f0 0%, #ffe7d5 100%);
      padding: 20px;
      border-radius: 8px;
      text-align: center;
      border: 2px solid #ff7a45;
    }
    .nutrition-value { font-size: 28px; font-weight: bold; color: #ff7a45; }
    .nutrition-label { color: #555; font-size: 12px; margin-top: 8px; font-weight: 600; }
    .nutrition-percent { font-size: 14px; color: #ff7a45; font-weight: 600; margin-top: 5px; }
    .pie-chart {
      display: flex;
      gap: 20px;
      margin: 20px 0;
      align-items: center;
      flex-wrap: wrap;
    }
    .pie-circle {
      width: 150px;
      height: 150px;
      border-radius: 50%;
      background: conic-gradient(
        #9254de 0deg calc(${proteinPercent * 3.6}deg),
        #faad14 calc(${proteinPercent * 3.6}deg) calc(${(proteinPercent + carbsPercent) * 3.6}deg),
        #ff7a45 calc(${(proteinPercent + carbsPercent) * 3.6}deg) 360deg
      );
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      font-size: 18px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .pie-legend {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .legend-item {
      display: flex;
      align-items: center;
      gap: 10px;
      font-size: 13px;
    }
    .legend-color {
      width: 16px;
      height: 16px;
      border-radius: 3px;
    }
    .exercise-summary {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 20px;
      margin-bottom: 20px;
    }
    .exercise-stat {
      background: linear-gradient(135deg, #fff1f0 0%, #ffccc7 100%);
      padding: 20px;
      border-radius: 8px;
      border: 2px solid #f5222d;
      text-align: center;
    }
    .exercise-stat.duration {
      background: linear-gradient(135deg, #f6f8fb 0%, #e6f2ff 100%);
      border-color: #1890ff;
    }
    .exercise-stat .value { font-size: 28px; font-weight: bold; color: #f5222d; }
    .exercise-stat.duration .value { color: #1890ff; }
    .exercise-stat .label { color: #555; font-size: 12px; margin-top: 8px; font-weight: 600; }
    .progress-grid {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 15px;
      margin-bottom: 30px;
    }
    .progress-card {
      background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%);
      padding: 20px;
      border-radius: 8px;
      border: 2px solid #1890ff;
      text-align: center;
    }
    .progress-card.goal {
      background: linear-gradient(135deg, #f6ffed 0%, #d9f7be 100%);
      border-color: #52c41a;
    }
    .progress-card.goal .value { color: #52c41a; }
    .progress-card.target {
      background: linear-gradient(135deg, #fff7e6 0%, #ffe8b6 100%);
      border-color: #faad14;
    }
    .progress-card.target .value { color: #faad14; }
    .progress-card .value { font-size: 24px; font-weight: bold; color: #1890ff; }
    .progress-card .label { color: #555; font-size: 12px; margin-top: 8px; font-weight: 600; }
    .tips-list {
      list-style: none;
      margin: 15px 0;
    }
    .tips-list li {
      padding: 10px;
      margin: 8px 0;
      background: #f9f9f9;
      border-left: 4px solid #52c41a;
      border-radius: 4px;
      font-size: 13px;
    }
    .footer {
      text-align: center;
      margin-top: 40px;
      padding-top: 20px;
      border-top: 2px solid #f0f0f0;
      color: #999;
      font-size: 11px;
    }
    .disclaimer {
      background-color: #fff7e6;
      border-left: 4px solid #faad14;
      padding: 15px;
      border-radius: 4px;
      margin-top: 20px;
      color: #d48806;
      font-size: 12px;
    }
    @media print {
      body { padding: 0; background: white; }
      .container { box-shadow: none; padding: 20px; }
      .page-break { page-break-after: always; }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>💪 ${getTranslation(locale, "title")}</h1>
      <p>${getTranslation(locale, "personalizedFor")} ${userName}</p>
      <p>${new Date().toLocaleDateString(locale === "en" ? "en-US" : "vi-VN", { year: "numeric", month: "long", day: "numeric" })}</p>
    </div>

    <div class="section page-break">
      <h2>📋 ${getTranslation(locale, "yourPlan")}</h2>
      <div class="summary">${sanitizeAndFormatText(plan.summary)}</div>
      <h2 style="margin-top: 30px;">📊 ${getTranslation(locale, "healthMetrics")}</h2>
      <div class="stats-grid">
        <div class="stat-card"><div class="stat-value">${plan.bmi}</div><div class="stat-label">${getTranslation(locale, "currentBMI")}</div></div>
        <div class="stat-card"><div class="stat-value">${plan.bmiCategory}</div><div class="stat-label">${getTranslation(locale, "category")}</div></div>
        <div class="stat-card"><div class="stat-value">${plan.timeline.weeksToGoal}</div><div class="stat-label">${getTranslation(locale, "weeksToGoal")}</div></div>
        <div class="stat-card"><div class="stat-value">${plan.timeline.weeklyWeightLoss}</div><div class="stat-label">${locale === "en" ? "kg/Week" : "kg/Tuần"}</div></div>
      </div>
    </div>

    <div class="section page-break">
      <h2>🍽️ ${locale === "en" ? "Nutrition Breakdown" : "Phân Tích Dinh Dưỡng"}</h2>
      <div style="background: white; padding: 20px; border-radius: 8px; border: 1px solid #f0f0f0; margin: 20px 0;">
        <div style="font-size: 16px; font-weight: 600; margin-bottom: 15px; color: #333;">${locale === "en" ? "Macro Distribution" : "Phân Bố Macro"}</div>
        <div class="pie-chart">
          <div class="pie-circle">${proteinPercent}%</div>
          <div class="pie-legend">
            <div class="legend-item"><div class="legend-color" style="background: #9254de;"></div><span>Protein: ${plan.nutrition.protein}g (${proteinPercent}%)</span></div>
            <div class="legend-item"><div class="legend-color" style="background: #faad14;"></div><span>Carbs: ${plan.nutrition.carbs}g (${carbsPercent}%)</span></div>
            <div class="legend-item"><div class="legend-color" style="background: #ff7a45;"></div><span>Fat: ${plan.nutrition.fat}g (${fatPercent}%)</span></div>
          </div>
        </div>
      </div>
      <h2 style="margin-top: 30px;">📊 ${locale === "en" ? "Daily Nutrition" : "Dinh Dưỡng Hàng Ngày"}</h2>
      <div style="background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%); padding: 20px; border-radius: 8px; margin-bottom: 20px;">
        <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 10px;">
          <span style="font-weight: 600;">${locale === "en" ? "Daily Calories" : "Calo/Ngày"}</span>
          <span style="font-size: 24px; font-weight: bold; color: #1890ff;">${plan.nutrition.dailyCalories} kcal</span>
        </div>
      </div>
      <div class="nutrition-grid">
        <div class="nutrition-item"><div class="nutrition-value">${plan.nutrition.protein}g</div><div class="nutrition-label">Protein</div><div class="nutrition-percent">${proteinPercent}%</div></div>
        <div class="nutrition-item" style="background: linear-gradient(135deg, #fff7e6 0%, #ffe8b6 100%); border-color: #faad14;"><div class="nutrition-value" style="color: #faad14;">${plan.nutrition.carbs}g</div><div class="nutrition-label">Carbs</div><div class="nutrition-percent" style="color: #faad14;">${carbsPercent}%</div></div>
        <div class="nutrition-item" style="background: linear-gradient(135deg, #fff1f0 0%, #ffccc7 100%); border-color: #f5222d;"><div class="nutrition-value" style="color: #f5222d;">${plan.nutrition.fat}g</div><div class="nutrition-label">Fat</div><div class="nutrition-percent" style="color: #f5222d;">${fatPercent}%</div></div>
      </div>
    </div>

    <div class="section page-break">
      <h2>💪 ${locale === "en" ? "Exercise Schedule" : "Lịch Tập Luyện"}</h2>
      <div class="exercise-summary">
        <div class="exercise-stat duration"><div class="value">${totalDuration}</div><div class="label">${locale === "en" ? "Total Minutes" : "Tổng Phút"}</div></div>
        <div class="exercise-stat"><div class="value">${totalCalories}</div><div class="label">${locale === "en" ? "Total Calories Burned" : "Tổng Calo Tiêu Thụ"}</div></div>
      </div>
      <table>
        <thead><tr><th>${locale === "en" ? "Day" : "Ngày"}</th><th>${locale === "en" ? "Activity" : "Hoạt Động"}</th><th>${locale === "en" ? "Duration (min)" : "Thời Lượng (phút)"}</th><th>${locale === "en" ? "Calories" : "Calo"}</th></tr></thead>
        <tbody>${exerciseTableRows}</tbody>
      </table>
    </div>

    <div class="section page-break">
      <h2>📈 ${locale === "en" ? "Weight Progress" : "Tiến Độ Giảm Cân"}</h2>
      <div class="progress-grid">
        <div class="progress-card goal"><div class="value">${plan.bmi}</div><div class="label">${locale === "en" ? "Current Weight" : "Cân Nặng Hiện Tại"}</div></div>
        <div class="progress-card target"><div class="value">${plan.timeline.weeksToGoal}</div><div class="label">${locale === "en" ? "Weeks Timeline" : "Thời Gian (Tuần)"}</div></div>
        <div class="progress-card"><div class="value">${plan.timeline.weeklyWeightLoss}</div><div class="label">${locale === "en" ? "Weight Loss/Week" : "Giảm/Tuần"}</div></div>
      </div>
      <div style="background: linear-gradient(135deg, #f0f5ff 0%, #e6f2ff 100%); padding: 20px; border-radius: 8px;">
        <ul class="tips-list">
          <li><strong>${locale === "en" ? "Timeline:" : "Thời Gian:"}</strong> ${plan.timeline.weeksToGoal} ${locale === "en" ? "weeks" : "tuần"} (${Math.round(plan.timeline.weeksToGoal / 4)} ${locale === "en" ? "months" : "tháng"})</li>
          <li><strong>${locale === "en" ? "Weekly Loss Rate:" : "Mức Giảm/Tuần:"}</strong> ${plan.timeline.weeklyWeightLoss} kg</li>
        </ul>
      </div>
    </div>

    <div class="section">
      <h2>💡 ${locale === "en" ? "Tips & Recommendations" : "Lời Khuyên & Gợi Ý"}</h2>
      <ul class="tips-list">
        <li>💧 ${locale === "en" ? "Drink enough water (2-3L per day) to stay hydrated" : "Uống đủ nước (2-3 lít/ngày)"}</li>
        <li>😴 ${locale === "en" ? "Get 7-8 hours of sleep daily for optimal recovery" : "Ngủ đủ 7-8 tiếng/ngày"}</li>
        <li>📊 ${locale === "en" ? "Stay consistent and track your weight weekly" : "Kiên trì & check weight hàng tuần"}</li>
        <li>🏥 ${locale === "en" ? "Consult a healthcare professional if needed" : "Tư vấn bác sĩ nếu cần"}</li>
        <li>🥗 ${locale === "en" ? "Focus on whole foods and balanced nutrition" : "Tập trung vào thực phẩm nguyên chất"}</li>
        <li>⏰ ${locale === "en" ? "Follow meal times consistently" : "Tuân thủ giờ ăn nhất quán"}</li>
      </ul>
      <div class="disclaimer">
        <strong>⚠️ ${locale === "en" ? "Important Disclaimer" : "Lưu Ý Quan Trọng"}</strong><br>
        ${locale === "en" ? "This plan is for reference only. Please consult a healthcare professional before starting any new exercise or diet program." : "Lộ trình này chỉ mang tính chất tham khảo. Vui lòng tư vấn với chuyên gia y tế trước khi bắt đầu chương trình."}
      </div>
    </div>

    <div class="footer">
      <p>${locale === "en" ? "Generated by Health AI Assistant" : "Được tạo bởi Health AI Assistant"} | ${new Date().toLocaleString(locale === "en" ? "en-US" : "vi-VN")}</p>
    </div>
  </div>
</body>
</html>`;
}
